# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    # configure resolvers
    resolvers:

        # setup the default resolver
        default:

            # use the default web path
            web_path: ~ #"%kernel.project_dir%/public"

    # your filter sets are defined here
    filter_sets:

        # use the default cache configuration
        cache: ~  

        about_me:


            quality: 100


            filters:


                thumbnail: { size: [140, 140], mode: outbound }

        
        product:


            quality: 100


            filters:


                thumbnail: { size: [500, 500], mode: outbound }

        carte:


            quality: 100


            filters:


                thumbnail: { size: [350, 350], mode: outbound }



