vich_uploader:
    db_driver: orm

    mappings:
        products:
            uri_prefix: /images/products
            upload_destination: '%kernel.project_dir%/public/images/products'
            namer: vich_uploader.namer_hash
            delete_on_remove: true
            delete_on_update: true
